appseguridad/urls.py
'''from rest_framework import routers
from appseguridad.api import UserViewSet
from django.urls import path,include



router_user = routers.DefaultRouter()
router_user.register(r'api/user', UserViewSet,'usuarios')'''


'''urlpatterns =[
    path('',include( router_user.urls)),
]
'''
'''
from django.urls import path,include,re_path
from appseguridad import api

urlpatterns =[
    path('login/',include(api.login)),
]'''

proypostgrado/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.documentation import include_docs_urls
from appseguridad.views.views import home, acceder, salir

from appevaluacion.views import evaluacion

urlpatterns = [
    #Borrar
    path('admin/', admin.site.urls),
    
    path('', acceder, name='login'),
    path('home/', home, name='home'),
    path('logout/',salir ,name="logout"),

    # Evaluaciones
    path('evaluacion/',include('appevaluacion.routes.evaluacion'),name="evaluacion"),
    path('filtrar/', evaluacion.filtrar_postulantes_evaluadores, name='filtrar_postulantes_evaluadores'),
    

    path('docs/', include_docs_urls(title='Api Documentation')),   
]

appevaluacion/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.core.validators import MaxValueValidator,MinValueValidator
from django.core.exceptions import ValidationError


SEXO = (('M', 'Masculino'),
        ('F', 'Femenino'),)

CARGO = (('Presidente','Presidente'),
         ('Secretario','Secretario'),
         ('Vocal','Vocal'))

class Modalidad(models.Model):
    idModalidad = models.AutoField(primary_key=True)
    des_modalidad = models.CharField(max_length=100, null=False)
    
    def __str__(self):
        return f'{self.des_modalidad}'

class Maestria(models.Model):
    idMaestria = models.AutoField(primary_key = True)   
    des_maestria = models.CharField(max_length=100, null=False)   
    
    def __str__(self):
        return f'{self.des_maestria}'

class Doctorado(models.Model):
    idDoctorado = models.AutoField(primary_key = True)   
    des_doctorado = models.CharField(max_length=100, null=False)    
    
    def __str__(self):
        return f'{self.des_doctorado}'
    
class Unidad(models.Model):
    idUnidad= models.AutoField(primary_key = True)   
    des_unidad = models.CharField(max_length=100, null=False)    
    
    def __str__(self):
        return f'{self.des_unidad}'

class Postulante(models.Model):
    idPostulante = models.AutoField(primary_key=True, null=False)   
    codigo = models.CharField(max_length=10, null=True)
    ap_paterno = models.CharField(max_length=100, null=False)
    ap_materno = models.CharField(max_length=100, null=False)
    nombres = models.CharField(max_length=100, null=False)    
    dni = models.CharField(max_length=20, null=False, unique = True)  
    email = models.EmailField(max_length=100, blank=True, null=True)
    celular = models.CharField(max_length=20, blank=True, null=True)    
    pdf_curriculum = models.CharField(max_length=200,blank=True, null=True)   
    doctorado = models.ForeignKey(Doctorado, on_delete = models.CASCADE, related_name='postulantes_doctorado', null=True, blank=True)   
    maestria = models.ForeignKey(Maestria, on_delete = models.CASCADE,related_name='postulantes_maestria', null=True, blank=True ) 
    unidad = models.ForeignKey(Unidad, null=True, on_delete = models.CASCADE)
    modalidad = models.ForeignKey(Modalidad, null=True, on_delete = models.CASCADE)

    def clean(self):
        # Validar que solo se haya ingresado una maestría o un doctorado, pero no ambos.
        if self.maestria and self.doctorado:
            raise ValidationError("Un postulante solo puede tener una maestría o un doctorado, no ambos.")
        if not self.maestria and not self.doctorado:
            raise ValidationError("Debe ingresar al menos una maestría o un doctorado.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.nombres} {self.ap_paterno} {self.ap_materno}'

class Evaluador(models.Model):
    idEvaluador = models.AutoField(primary_key=True, null=False)
    codigo_evaluador = models.CharField(max_length=10, unique=True, editable=False) 
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=100, null=False)
    apellidos = models.CharField(max_length=100, null=False)
    dni = models.CharField(max_length=8, null=True)    
    email = models.EmailField(max_length=100, null=True)      
    activo = models.BooleanField(default= True)
    cargo = models.CharField(max_length=20, choices=CARGO, default='Presidente')
    unidad = models.ForeignKey(Unidad, null=True, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.nombres} {self.apellidos}'

class Evaluacion(models.Model):
    idEvaluacion= models.AutoField(primary_key=True, null=False)
    codigo_evaluacion = models.CharField(max_length=10,unique = True, null=True)
    estado_evaluacion = models.BooleanField(default= False)
    postulante = models.ForeignKey(Postulante,unique = True , on_delete = models.CASCADE)
    evaluador = models.ForeignKey(Evaluador, on_delete = models.CASCADE)    
    fecha_creacion = models.DateField(default=date.today)
  
    def __str__(self):
        return f'Datos Evaluacion {self.codigo_evaluacion}: {self.evaluador} | {self.postulante}'
     
class DetalleEvaluacion(models.Model):
    idDetalleEva = models.AutoField(primary_key=True, null = False)
    evaluacion = models.ForeignKey(Evaluacion,unique = True ,on_delete = models.CASCADE, null = False)
    puntaje_promedioP = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(6.00), MaxValueValidator(12.00)], null=False, default=6.00)
    puntaje_cursosEva = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00), MaxValueValidator(4.00)] , null=False, default=0)
    puntaje_partCientifica = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00), MaxValueValidator(4.00)], null=False, default=0)
    puntaje_docenciaUni = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.50), MaxValueValidator(3.00)], null=False, default=0.50)
    puntaje_idiomaExt = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.50), MaxValueValidator(1.00)], null=False, default=0.50)
    puntaje_capacitacion = models.DecimalField(max_digits=5,decimal_places=2, validators=[MaxValueValidator(24.00)], null=False, default=0) # Primer Subtotal
    puntaje_libroInscritos = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00), MaxValueValidator(2.00)], null=False, default=0)
    puntaje_publicaciones = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00), MaxValueValidator(3.00)], null=False, default=0)
    puntaje_proyInvestig = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00)], null=False, default=0)
    puntaje_asesoriaProy = models.DecimalField(max_digits=5,decimal_places=2, validators=[MinValueValidator(0.00)], null=False, default=0)
    puntaje_produccionCien = models.DecimalField(max_digits=5,decimal_places=2, validators=[MaxValueValidator(11.00)], null=False, default=0)  # Segundo Subtotal
    puntajeFinal = models.DecimalField(max_digits=5,decimal_places=2, validators=[MaxValueValidator(35.00)], null=False, default=0) # Primer Subtotal +  Segundo Subtotal

    def __str__(self):
        return f'Detalla: {self.puntaje_capacitacion} + {self.puntaje_produccionCien} = {self.puntajeFinal}'

proypostgrado/templates/plantilla.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">  

    <title> {% block title %} {% endblock %}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;700;900&family=Poppins:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '/adminlte/dist/css/adminlte.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block css %} {% endblock %}
    <style>
      :root {
        --font-size: 1;
      }
      body{
        font-family: 'Poppins', sans-serif;
        font-size: calc(var(--font-size) * 0.9em)
      }
      .sidebar-dark-primary{
        background: url("{% static 'adminlte/dist/img/bg-01.jpg' %}") no-repeat center center fixed;
	      background-size: cover;
      }
      .nav-link,.nav-header{
        color: #000!important;
      }
      .brand-text{
        color: #0D1C31!important;
        font-weight: bold!important;
        font-family: 'Poppins', sans-serif;

      }  
    


    </style>
  </head>
  
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button">
        <i class="fas fa-bars"></i>
        </a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home' %}" class="nav-link">Home</a>  
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">   
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <div class="user-panel d-flex">            
            <div class="info" id="UserLogged-info">{{request.user.username}}</div>
            <div class="image">
              <img src="{% static 'adminlte/dist/img/user2-160x160.png'%}" class="img-circle elevation-2" alt="User Image">
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">Mi Perfil</a>         
          <div class="dropdown-divider"></div><a href="{% url 'logout' %}" class="dropdown-item"><i class="fa fa-power-off"></i> Salir</a>      
        </div>
      </li>         
    </ul>
  </nav>  
  <!-- /.navbar -->


  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    
    <!-- Brand Logo -->
    <a href="{% url 'home' %}" class="brand-link" style="text-decoration: none;"> 
      <img src="{% static 'adminlte/dist/img/logount.png'%}" class="brand-image img-circle elevation-3" style="height:75px;">
      <span class="brand-text font-weight-light">POSGRADO</span>
    </a>

    <!-- Sidebar Menu -->
    <div class="sidebar">
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          {% if perms.appevaluacion.view_doctorado %}
          <!-- Dashboard -->
          <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link ">
              <p style="font-weight: bold;">
                DASHBOARD
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>             
          </li>
          {% endif %}
          {% if perms.appevaluacion.view_doctorado %}
          <!-- Accesos -->
          <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link ">
              <p style="font-weight: bold;">
                ACCESOS
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              
              <li class="nav-item">
                <a href="#" class="nav-link">            
                  <i class="nav-icon fas fa-address-card"></i>
                  <p>
                    Perfil del Usuario
                  </p>
                </a>
              </li>
                            
              <li class="nav-item">
                <a href="#" class="nav-link">          
                  <i class="nav-icon fas fa-solid fa-user"></i>
                  <p>
                    Usuarios
                  </p>
                </a>
              </li>           
            </ul>
          </li>
          {% endif %}
          {% if perms.appevaluacion.view_doctorado %}
          <!-- Registros -->
          <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link">              
              <p style="font-weight: bold;">
                REGISTROS
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
           
            <ul class="nav nav-treeview">                    
              <li class="nav-item">
                <a href="#" class="nav-link"> 
                  <i class="nav-icon fas fa-address-book"></i>
                  <p>
                    Evaluadores
                  </p>
                </a>
              </li>                
          
              <li class="nav-item">
                <a href="#" class="nav-link">  
                  <i class="nav-icon fas fa-list-alt"></i>
                  <p>
                    Postulantes
                  </p>
                </a>
              </li>            
              {% endif %}
          <!-- Procesos -->        
          <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link">
              <p style="font-weight: bold;">
                PROCESOS
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">             
              <li class="nav-item">
                <a href="{% url 'listar_evaluacion' %}" class="nav-link">
                  <i class="nav-icon fas fa-receipt"></i>
                  <p>
                    Evaluaciones
                  </p>
                </a>
              </li>                         
            </ul>
          </li>

        </ul>
      </nav>
    </div>
  </aside>

  <!--  fa-solid fa-person Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    {% comment %} <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{% block titleContent %} {% endblock %}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>

              <li class="breadcrumb-item active">Blank Page</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section> {% endcomment %}

    <!-- Main content -->
    <section class="content">
    {% block content %}
    
   
    {% endblock %}
    </section>
    <!-- /.content -->
   
  
   

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-center d-none d-sm-block">
     <b>Escuela de Postgrado</b>| Universidad Nacional de Trujillo
    </div>
  </footer>


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
  <!--- jQuery -->
  {% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> {% endcomment %}

  <script src="{% static '/adminlte/plugins/jquery/jquery.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="{% static '/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}">  </script>
  <!-- AdminLTE App -->
  <script src="{% static '/adminlte/dist/js/adminlte.min.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static '/adminlte/dist/js/demo.js' %}"></script>


 <!--  <script>
    {% if userNameLogged %}    
        localStorage.setItem('userNameLogged', "{{userNameLogged}}");
    {% endif %}
    {% if userLogged %}    
        localStorage.setItem('userLogged', "{{userLogged}}");
    {% endif %}
    let user_name = localStorage.getItem('userNameLogged');
    document.getElementById('UserLogged-info').innerHTML = user_name;
</script> -->
{% block js %}
{% endblock %}
</body>
</html>